# Generated by Django 4.2.5 on 2023-09-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personfilmwork',
            table='content"."person_film_work',
        ),
    ]
